default:
  image: ubuntu:latest
  before_script: |
    apt-get update
    apt-get install -y python3-venv make

build:
  stage: build
  script: make build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script: make test
  needs: []
mypy:
  stage: test
  script: make mypy
  needs: []
flake8:
  stage: test
  script: make flake8
  needs: []
install:
  stage: test
  script:
    - python3 -m venv .venv
    - .venv/bin/pip install dist/*.whl
