default_install_hook_types: [commit-msg, pre-commit, pre-merge-commit, pre-push]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=100]
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-illegal-windows-names
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: name-tests-test
  - id: pretty-format-json
    args: [--autofix, --ident=4, --no-sort-keys]
  - id: requirements-txt-fixer
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
  - id: pyupgrade
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.0.3
  hooks:
  - id: editorconfig-checker
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
  - id: gitlint-ci
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.43.0
  hooks:
  - id: markdownlint
- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint
- repo: https://github.com/rstcheck/rstcheck
  rev: v6.2.4
  hooks:
  - id: rstcheck
- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [--filter-files, --verbose, --color, --jobs=-1]
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    args: [--ignore=E203, --color=always]  # spacing around ':' slicing-syntax
    additional_dependencies: [pep8-naming]
- repo: local
  hooks:
  - id: pytest
    name: run test
    entry: make test
    language: system
    pass_filenames: false
    types: [python]
  - id: mypy
    name: run mypy
    entry: make mypy
    language: system
    pass_filenames: false
    types: [python]
