name: Global
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit 'manual' hooks
      run: pre-commit run --color=always
        --all-files
        --hook-stage manual
        --show-diff-on-failure
        --verbose
