name: Python
on: [push]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit 'manual' hooks
      run: pre-commit run --color=always
        --all-files
        --hook-stage manual
        --show-diff-on-failure
        --verbose
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build project
      run: make build
    - uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.python-version }}
        path: dist
  run:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ matrix.python-version }}
    - name: Install package
      run: pip install *.whl
    - name: Run project
      run: python -m template
  run-windows:
    needs: [build]
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ matrix.python-version }}
    - name: Install package
      run: pip install (get-item .\*.whl)
    - name: Run package
      run: python -m template
  run-macos:
    needs: [build]
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist-${{ matrix.python-version }}
    - name: Install package
      run: pip install *.whl
    - name: Run package
      run: python -m template
